NodeOUs:
 Enable: true
 ClientOUIdentifier:
   Certificate: cacerts/ca-beta-olympus-pt-7055.pem
   OrganizationalUnitIdentifier: client
 PeerOUIdentifier:
   Certificate: cacerts/ca-beta-olympus-pt-7055.pem
   OrganizationalUnitIdentifier: peer
 AdminOUIdentifier:
   Certificate: cacerts/ca-beta-olympus-pt-7055.pem
   OrganizationalUnitIdentifier: admin
